name: names_translation
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - absl-py=0.9.0
  - astor=0.8.1
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - cachetools=4.1.1
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - gast=0.2.2
  - google-auth=1.20.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - idna=2.10
  - importlib-metadata=1.7.0
  - intel-openmp=2020.1
  - joblib=0.16.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - libprotobuf=3.12.4
  - markdown=3.2.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - numpy=1.19.1
  - oauthlib=3.1.0
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - pandas=1.1.0
  - pip=20.2.2
  - protobuf=3.12.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyreadline=2.1
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.32.3
  - tensorboard=2.2.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - urllib3=1.25.10
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - werkzeug=0.14.1
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.12.1
  - zipp=3.1.0
  - zlib=1.2.11
