name: names_translation
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - intel-openmp=2020.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - mkl=2020.1
  - numpy=1.19.1
  - openssl=1.1.1g
  - pandas=1.1.0
  - pip=20.2.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.35.1
  - wincertstore=0.2
