name: names_translation
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - pandas=1.1.0
  - scikit-learn=0.23.2
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - tqdm=4.50.0
  - typer=0.3.1
  - pip
  - pip:
    - streamlit==0.69.1
